### ISSUE TITLE
Errors in Documents

### ISSUE THREAD

**Issue by Nisgrak** [DM164/Dark-by-DM#13]
Hi!

In the navigate section in the left has a white fade
![image](https://user-images.githubusercontent.com/19597708/90916186-ead18300-e3e0-11ea-93a9-1c7771152b87.png)

The color of the hover is a bit unreadable
![image](https://user-images.githubusercontent.com/19597708/90916193-edcc7380-e3e0-11ea-8e63-05124b73a651.png)

In https://docs.google.com/document/u/0/ the top bar is white, and if expand the left also is white
![image](https://user-images.githubusercontent.com/19597708/90916444-5c113600-e3e1-11ea-9994-fdde660c78e8.png)

Thanks for your work.

**Comment by DM164** [comment]
Fixed in 1.6.6
