### ISSUE TITLE
Option to light links color in Google

### ISSUE THREAD

**Issue by Nisgrak** [DM164/Dark-by-DM#14]
Hi!

Your style for google is nice but I want to see the link like in light(default) google, you use the same color when a link is unvisited in light and visited in your theme, its confusing for me.

Unvisited
![image](https://user-images.githubusercontent.com/19597708/91059303-d633fb80-e629-11ea-9516-058a0dd70b81.png)
![image](https://user-images.githubusercontent.com/19597708/91059425-fd8ac880-e629-11ea-908a-80b82364d674.png)

Visited
![image](https://user-images.githubusercontent.com/19597708/91059389-efd54300-e629-11ea-83bc-828cc3495d21.png)
![image](https://user-images.githubusercontent.com/19597708/91059420-f9f74180-e629-11ea-85c0-1f0da641f151.png)

**Comment by DM164** [comment]
Sorry but I don't quite get what needs to be changed. Links that haven't been opened yet are white and links that have been opened are blue. Maybe I got it wrong, could you highlight the part you want to be changed in red?
Thanks for taking your time though and helping improve these styles :)

**Comment by Nisgrak** [comment]
I create a PR, I think is more clear the example 😉

**Comment by DM164** [comment]
Oh ok now I get it and also thanks for contributing to the project. 👍
