### ISSUE TITLE
"It looks like there aren't any great matches for your search" bug

### ISSUE THREAD

**Issue by wadawada** [DM164/Dark-by-DM#16]
Hello, the text "there aren't any great matches..." in the following link is too dark to see in the dark background. 
Please fix it thanks

https://www.google.com/search?rlz=1C1CHBF_enUS844US844&sxsrf=ALeKk000kyyFEKmO1JxtYrLLMYgIXhIMQw%3A1598373891852&ei=A0BFX_TGM4bM-gTXiL24DA&q=catuskoti+l+%E6%96%87&oq=catuskoti+l+%E6%96%87&gs_lcp=CgZwc3ktYWIQAzIFCCEQoAEyBQghEKABMgUIIRCgATIFCCEQoAE6BAgAEEc6AggAOgQIABAeOgYIABAWEB46BQgAEM0CUJmhE1jepxNg86oTaABwAXgAgAGCA4gBzAuSAQcwLjMuMC4zmAEAoAEBqgEHZ3dzLXdpesABAQ&sclient=psy-ab&ved=0ahUKEwi01Krg5rbrAhUGpp4KHVdED8cQ4dUDCA0&uact=5

**Comment by DM164** [comment]
Thanks for letting me know, it's now fixed in the newest version.
Have a nice day!
