### ISSUE TITLE
Display images? row is not styled

### ISSUE THREAD

**Issue by Neobond** [DM164/Dark-by-DM#19]
Display images row is not styled dark. If it makes a difference I am using gmail through G Suite.

![SNAG-0002](https://user-images.githubusercontent.com/42996358/92582874-d1aa4c80-f291-11ea-93b2-1c50ea2fd60f.png)

Great theme btw!

**Comment by DM164** [comment]
Thanks for the feedback, I'm going to fix this soon.
Have a nice day!

**Comment by Geeyun-JY3** [comment]
`Woohoo! You've read all the messages in your inbox.` row also
![image](https://user-images.githubusercontent.com/49396421/97082232-ca20e600-163a-11eb-8463-d5e82c742491.png)

**Comment by simbabque** [comment]
> `Woohoo! You've read all the messages in your inbox.` row also
> ![image](https://user-images.githubusercontent.com/49396421/97082232-ca20e600-163a-11eb-8463-d5e82c742491.png)

My PR #43 fixes this.

**Comment by DM164** [comment]
I'm a bit late but still wanted to say thanks for the fix.
Have a nice one!
