### ISSUE TITLE
White areas in gmail compose window

### ISSUE THREAD

**Issue by pabloh84** [DM164/Dark-by-DM#20]
That's basically it. See attached image for details. 

EDIT: I've realized that this behaviour only occurs when you have configured gmail as the handler (chrome://settings/handlers) for mailto links ([mailto:someone@somewhere.com](mailto:someone@somewhere.com)). On pressed a compose only window is opened and the issue is reproduced. 

PD.- BTW Thanks for the great work! 

![2020-09-10_12-23](https://user-images.githubusercontent.com/7147388/92717439-785d1e80-f360-11ea-975f-9c1cfc626723.png)

**Comment by DM164** [comment]
Thanks for the feedback, it's now fixed in the latest version.
Have a nice day!

**Comment by pabloh84** [comment]
Confirmed! Thanks!
