### ISSUE TITLE
Drive titlebar is white

### ISSUE THREAD

**Issue by Nisgrak** [DM164/Dark-by-DM#22]
Hi!

The titlebar in drive is white

![image](https://user-images.githubusercontent.com/19597708/92995238-0f151100-f502-11ea-9464-7723b2d87b40.png)

As always, thanks for your work.

**Comment by xnaas** [comment]
Google has the background color hardcoded. No matter what is put into Stylus, it's overridden by Google's HTML. I don't know if this one is solvable with Stylus.

By all rights, this should work:

```
#gb.gb_ta.gb_4a.gb_7e.gb_8d {
        background-color:rgba(47,47,47,1);
    }
```

But it doesn't because Google has this set:

```
<header class="gb_ta gb_4a gb_7e gb_8d" ng-non-bindable="" id="gb" role="banner" style="background-color:rgba(255,255,255,1);">
```

No matter what, that `style="background-color:rgba(255,255,255,1);` seems to override anything you put into Stylus.

**Comment by Nisgrak** [comment]
@xnaas I modify the style and with `!important` and without the class `gb_8d` its change the color of the header without problem.

```css
#gb.gb_ta.gb_4a.gb_7e {
     background-color: #232323 !important;
}
```

![image](https://user-images.githubusercontent.com/19597708/93180251-2ee14a80-f737-11ea-9cb4-537aabdac18b.png)

**Comment by DM164** [comment]
Yeah I know, this has always been an issue, I've been constantly updating this but it always keeps getting broken.
If anyone finds a good solution, I'd be really thankful. At the moment the only permanent fix I can think of at this point is maybe to use the filter/invert property but I don't really like the idea of doing it that way.

**Comment by Nisgrak** [comment]
Maybe you can use `header` as selector, searching in the page it's not another one and for the semantic of HTML shouldn't have another never.

```css
header {
     background-color: #232323 !important;
}
```

**Comment by DM164** [comment]
Oh thanks that might actually be it, I'll add this to the code!
