### ISSUE TITLE
Dark Google DM - Images link

### ISSUE THREAD

**Issue by MoneyAllDay** [DM164/Dark-by-DM#24]
Perhaps you should also add the link "https://images.google.com/" to the url list or just edit the regexp a bit.

Thanks for the themes.

**Comment by DM164** [comment]
Can you please maybe go more into detail. Why should I add this feature and how.
Thanks for contributing and stay safe!

**Comment by MoneyAllDay** [comment]
I'm sorry if i wasn't clear, all i meant to say is that the theme is not active at the link "https://images.google.com/" when it should be.

That's why i said to add the link to the url list or edit the current regexp ones on the theme [like so](https://i.imgur.com/14rA3JC.gif).

**Comment by DM164** [comment]
Oh ok thanks, I added it now.
Thanks for the feed back and stay safe!
