### ISSUE TITLE
Drive new folder and rename

### ISSUE THREAD

**Issue by Nisgrak** [DM164/Dark-by-DM#26]
The new folder and rename is in white

![image](https://user-images.githubusercontent.com/19597708/94946281-28472700-04dc-11eb-97ec-bdf97206311b.png)
![image](https://user-images.githubusercontent.com/19597708/94946451-73613a00-04dc-11eb-96ab-351615ee41b7.png)

**Comment by DM164** [comment]
Thanks for the feedback, it's now fixed in the newest version (3.3.2).
Have a nice day!
