### ISSUE TITLE
Fixes for the header on contacts.google.com in the Dark Gmail by DM userstyle:

### ISSUE THREAD

**Issue by brian6932** [DM164/Dark-by-DM#27]
header .gb_4d{
		background-color: #2b2b2b;
        color: #efefef;
	}
	.gb_7d.gb_0e .gb_Re .gb_5e {
    background-color: #1f1f1f;
    border: 1px solid transparent;
    -webkit-border-radius: 8px;
    border-radius: 8px;
    margin-left: auto;
    margin-right: auto;
    max-width: 720px;
    position: relative;
    -webkit-transition: background 100ms ease-in,width 100ms ease-out;
    transition: background 100ms ease-in,width 100ms ease-out;
	}

**Comment by DM164** [comment]
Thanks for contributing to the style.
Have a nice day and stay safe!
