### ISSUE TITLE
lightening icons

### ISSUE THREAD

**Issue by EVale** [DM164/Dark-by-DM#28]
Sorry for the low-level question but how do I change the color of the icons? Having them dark-on-dark makes them barely distinct from background but I am not able to find the lines where I can exactly change those.

Thanks for this very nice work!

**Comment by DM164** [comment]
If we are talking about Dark Gmail, there should be a menu where you can select themes. There choose the default one. If not it might be a bug, in that case it would be nice if you could share a screenshot.
Have a nice day and stay safe!

**Comment by EVale** [comment]
Hi Denis,

yes sorry I meant the gmail app.
It does actually looking better than I remember now though I wanted to take
off the blue text in emails and increase contrast for checkbox.
Can you give me pointers?


[image: image.png]

[image: image.png]

Thanks!

E

**Comment by EVale** [comment]
Ma sei Italiano?

Here is another thing I just noticed. Text becomes almost invisible in this
email (I had to highlight it)
Sorry if this is annoying you I am no programmer so I am not sure how to
change this stuff.

Grazie!
e
[image: image.png]

**Comment by DM164** [comment]
I'm sorry but I cant view the images, could you try and upload them through GitHub or maybe contact me through my Discord? (https://discord.gg/8c6gXwz)
Have a nice day!
PS. Si sono italiano :)
