### ISSUE TITLE
[Dark Google] Knowledge Panel Box is not styled

### ISSUE THREAD

**Issue by zeroxxx2** [DM164/Dark-by-DM#29]
![image](https://user-images.githubusercontent.com/19965111/96698881-d2b5ba00-13b7-11eb-875d-a7384cd16401.png)

Take a look, its background is white.

I'm on the latest Firefox 81.0.2/Win10 x64.

**Comment by DM164** [comment]
Hi thanks for the feedback this should be fixed in the latest versions. Let me know if there's still something not working.
Have a nice day!
