### ISSUE TITLE
UserCSS support

### ISSUE THREAD

**Issue by weakit** [DM164/Dark-by-DM#3]
This isn't an actual issue, but more of a request:
Could you make your themes into [UserCSS ](https://github.com/openstyles/stylus/wiki/UserCSS) and host it on GitHub? 

I think that would make it a lot easier for people to install and update. I'd be glad to help.
Thanks.

**Comment by DM164** [comment]
Hi thanks for the suggestion, I looked at it now and I'm probably going to do it this way from now on. 
Have a nice day and stay safe!

**Comment by weakit** [comment]
Thanks a bunch!
