### ISSUE TITLE
[google.user.css] Color fault collection

### ISSUE THREAD

**Issue by Tiippex** [DM164/Dark-by-DM#36]
Hello,

I tested a bit with v7.25.0 and took some screenshots of tiny issues.

I hope that helps somehow.

Wrong textcolor:
![image](https://user-images.githubusercontent.com/16509128/102181618-371e6280-3eab-11eb-9a65-b9efd1c6da4d.png)
![image](https://user-images.githubusercontent.com/16509128/102181700-659c3d80-3eab-11eb-8586-bbdb96afc9ac.png)
![image](https://user-images.githubusercontent.com/16509128/102182045-e78c6680-3eab-11eb-82ad-e36ad11274ee.png)

Wrong background color:
![image](https://user-images.githubusercontent.com/16509128/102181760-79e03a80-3eab-11eb-89cc-ee42f19672d9.png)
![image](https://user-images.githubusercontent.com/16509128/102181838-92505500-3eab-11eb-9fda-0d4f00ac30a2.png)
![image](https://user-images.githubusercontent.com/16509128/102182112-0559cb80-3eac-11eb-94ea-173f695a87f7.png)

**Comment by DM164** [comment]
Thanks for the feedback, most of these issues should be fixed in the latest update!
