### ISSUE TITLE
Drive has big white areas

### ISSUE THREAD

**Issue by CumpsD** [DM164/Dark-by-DM#4]
What do I need to provide you to help to debug this?

See screenshot:

![image](https://user-images.githubusercontent.com/1201644/87549965-c9c59600-c6ae-11ea-8a37-85ee69ad560f.png)

**Comment by DM164** [comment]
Hi, thanks for your feedback and sorry for responding late.
I've taken a look at it and for me it works fine, do you have any other
extensions installed that might cause issues with my style?

**Comment by CumpsD** [comment]
No, only your style. It is in the priority view, do you have this?

https://drive.google.com/drive/priority

**Comment by DM164** [comment]
I tried to open the priority view but can't get into it, maybe it's a new feature introduced that is rolling out or is there a setting for it?

**Comment by CumpsD** [comment]
Does this help? https://support.google.com/drive/thread/4740661?hl=en

**Comment by DM164** [comment]
Oh ok so it's a G-Suite feature. I currently don't have an account with G-Suite but I'll start the free trial and style it in the following days.

**Comment by DM164** [comment]
> Oh ok so it's a G-Suite feature. I currently don't have an account with G-Suite but I'll start the free trial and style it in the following days.

This should finally be fixed, it took a long time but thanks to a pull request I got my hands on the code. I hope it works on Google Drive too.
