### ISSUE TITLE
White bar on top of google images search

### ISSUE THREAD

**Issue by NazZaR** [DM164/Dark-by-DM#42]
https://www.google.com/search?q=elm327&hl=en&sxsrf=ALeKk03_QaQDr8bLHanPU8yAxegwh5ikNQ:1614160143531&source=lnms&tbm=isch&sa=X&biw=1686&bih=1284
![image](https://user-images.githubusercontent.com/5753530/108982330-de8ff080-76b7-11eb-8086-3ea035546069.png)

**Comment by DM164** [comment]
Fixed in the latest update
