### ISSUE TITLE
Docs has white top header

### ISSUE THREAD

**Issue by CumpsD** [DM164/Dark-by-DM#5]
What do I need to provide to help you debug this?

See screenshot:

![image](https://user-images.githubusercontent.com/1201644/87550063-e8c42800-c6ae-11ea-92b2-44ea9ca03d68.png)

**Comment by DM164** [comment]
Hi, thanks for your reply and sorry for the late reply.
I'm going to look into it and fix it.
Watch out for an update tomorrow.
Have a great day!

**Comment by DM164** [comment]
Fixed in today's update.

**Comment by CumpsD** [comment]
The header is fixed, but there is still this part, is that possible to fix too?

![image](https://user-images.githubusercontent.com/1201644/89100783-618aea00-d3fa-11ea-806e-0bf2ceb2235c.png)

**Comment by DM164** [comment]
Thanks for the feedback I will look into it and fix it.
