### ISSUE TITLE
Dark Google by DM: change clicked links to other color

### ISSUE THREAD

**Issue by wadawada** [DM164/Dark-by-DM#54]
In white/default mode, the colors of links and other texts are never the same.
In dark mode, the clicked link has the same color(white) as the search result, which can be confusing because users don't know if it is a link unless it is hovered.
Please change the clicked link color to other color so that it is also readable in dark mode thanks
(if I use default links option, the clicked link color are too dark in dark mode which makes them unviewable)

**Comment by DM164** [comment]
Hi thanks for the feedback, I'm a bit late but I invite you to read this new issue I opened today: #63 
Have a nice day!
