### ISSUE TITLE
covid chart too dark in google search

### ISSUE THREAD

**Issue by wadawada** [DM164/Dark-by-DM#56]
![image](https://user-images.githubusercontent.com/9424144/113931243-173ae380-97a7-11eb-822c-bd942bd5adf4.png)

![image](https://user-images.githubusercontent.com/9424144/113931281-228e0f00-97a7-11eb-8575-11c6d7295464.png)

**Comment by DM164** [comment]
Hi I'm late at responding because I forgot, but I fixed the issue and wanted to thank you for the feedback.
Take a look at #63 for further info about the theme too.
Stay safe and have a nice day!
