### ISSUE TITLE
Double text while writting in search bar

### ISSUE THREAD

**Issue by borjagarciab** [DM164/Dark-by-DM#57]
Hello,
This is a screenshot about the problem
https://gyazo.com/2c2f9432feddff089f1f08d130a74cb7

To fix it, i have seen in class ".gsfi"  , disabling the "line-height" it works ok.
A gif where u can see:
https://gyazo.com/558757b3100acd89139b44c6e9fd5cbf

**Comment by DM164** [comment]
Hi thanks for letting me know, I'm aware of the issue but I won't be working on Dark Google by DM anymore since Google is releasing an official dark mode for the search engine
#63 
Stay safe and have a nice day!
