### ISSUE TITLE
Instagram livestreams 

### ISSUE THREAD

**Issue by sn3akyb3ar** [DM164/Dark-by-DM#58]
Comments section during Instagram livestreams is bright white.

![image](https://user-images.githubusercontent.com/34551334/123483522-83dbb680-d60f-11eb-925f-84d240aa39ab.png)

**Comment by DM164** [comment]
Hi, thanks for the feedback I will be fixing this bug in the next update!

**Comment by DM164** [comment]
Hi, I've fixed the issue in the latest version!
