### ISSUE TITLE
Gmail has a mix of white and black preview panel

### ISSUE THREAD

**Issue by CumpsD** [DM164/Dark-by-DM#6]
What do I need to provide to help you?

Default Gmail theme enabled.

See screenshot:

![image](https://user-images.githubusercontent.com/1201644/87550270-2e80f080-c6af-11ea-953f-bba7442ccd74.png)

**Comment by ngouy** [comment]
Another exemple in panel preview too

![image](https://user-images.githubusercontent.com/12391171/87683900-9ab33100-c74f-11ea-8b22-c1be4ea0013c.png)

**Comment by DM164** [comment]
Thanks for the feedback!
I'm going to fix this in the next version with the information provided.
Have a great day!

**Comment by CumpsD** [comment]
It is partially fixed:

![image](https://user-images.githubusercontent.com/1201644/89061959-eb3ca800-d365-11ea-8b39-9790a68585e1.png)

**Comment by DM164** [comment]
Thanks for lettings me know I'm going to take a look and try to fix it.

**Comment by DM164** [comment]
Ok so far I've fixed the split pane view. The calendar preview in this one still needs to be restyled.

> Another exemple in panel preview too
> 
> ![image](https://user-images.githubusercontent.com/12391171/87683900-9ab33100-c74f-11ea-8b22-c1be4ea0013c.png)
> 
> * same issue if its bellow or on the right side
>   ![image](https://user-images.githubusercontent.com/12391171/87685083-fdf19300-c750-11ea-9a3f-f4bb28254e7d.png)

**Comment by DM164** [comment]
Forgot to get back to this issue but everything should be solved
