### ISSUE TITLE
Uninstall dark mode for Gmail

### ISSUE THREAD

**Issue by kimjant** [DM164/Dark-by-DM#64]
How do I uninstall dark mode for Gmail on my MacBook Pro? Sorry if this is a silly question.

**Comment by DM164** [comment]
You have to open the stylus extension on your browser and select "Manage". There you will find a list of style and you can click on the "X" to delete a style.

**Comment by kimjant** [comment]
Thank you so much, I found it!

**Comment by DM164** [comment]
No problem 👌
