### ISSUE TITLE
Dark Gmail loses color for "draft" marker

### ISSUE THREAD

**Issue by durka** [DM164/Dark-by-DM#66]
In regular Gmail, including dark mode, a saved draft shows up red in the conversation list. The Dark Gmail rule for `.yP` overrides this. Another rule such as the following is required to restore it:

```
.boq {
    color: #be2501;
}
```

![image](https://user-images.githubusercontent.com/47007/138209576-6cfb7f3c-7c86-4825-a4d4-13f9621ba749.png)

**Comment by DM164** [comment]
Thanks for letting me know, I've added your line in the latest update to restore the red color.
Have a nice day! 👍
