### ISSUE TITLE
Search bar using black text

### ISSUE THREAD

**Issue by dagumak** [DM164/Dark-by-DM#68]
I just wanted to report this. Happy to submit a PR, but not sure which CSS to change.

<img width="994" alt="Screen Shot 2021-12-09 at 13 49 33" src="https://user-images.githubusercontent.com/1531559/145336423-4faf87a2-975c-4a1a-aa1f-9baf941de41c.png">

**Comment by DM164** [comment]
Hi thanks for your feedback, I fixed it in the latest update 👍
