### ISSUE TITLE
GMAIL Priority inbox : sections Titles are black

### ISSUE THREAD

**Issue by ngouy** [DM164/Dark-by-DM#7]
![image](https://user-images.githubusercontent.com/12391171/87685930-ec5cbb00-c751-11ea-8021-de0649ed9ed0.png)
![image](https://user-images.githubusercontent.com/12391171/87685951-f41c5f80-c751-11ea-847d-1f5f94395d36.png)

**Comment by DM164** [comment]
Sorry for responding so late, I'm going to take a look at it and fix it.
Thanks for the feedback and have a nice day!

**Comment by DM164** [comment]
I've fixed it in the newest version.
