### ISSUE TITLE
Define `@homepageURL` for every UserCSS style in this repository

### ISSUE THREAD

**Issue by Geeyun-JY3** [DM164/Dark-by-DM#8]
Define `@homepageURL` for every UserCSS style in this repository. The URL can be `https://dark-by-dm-website.now.sh/` or `https://github.com/DM164/Dark-by-DM`

**Comment by DM164** [comment]
Thanks for the suggestion, I just added the homepage

**Comment by Geeyun-JY3** [comment]
@DM164 What I mean is that defining the `@homepageURL` in the UserCSS metadata can make the homepage icon (![external-link](https://user-images.githubusercontent.com/136959/44557521-5d30ff00-a704-11e8-8727-75001af6a0e4.png)) be present, as is mentioned in Stylus wiki: https://github.com/openstyles/stylus/wiki/UserCSS-authors#homepageurl
(You can also refer to: https://github.com/openstyles/stylus/wiki/Manager#homepage, https://github.com/openstyles/stylus/wiki/UserCSS-authors#managing)

I forgot to post these links… My bad🤦‍♂️

**Comment by DM164** [comment]
Oh ok thanks for sending the links, I'll take a look.
