### ISSUE TITLE
Sheets formula bar difficult to read

### ISSUE THREAD

**Issue by jamerst** [DM164/Dark-by-DM#9]
The contents of the current cell are difficult to read due to the text being grey on a white background.

![image](https://user-images.githubusercontent.com/10601770/89338380-666aca80-d694-11ea-990d-18862c0c3aaf.png)

**Comment by DM164** [comment]
I fixed this in the latest update, I'm also going to focus more on Dark Google Docs now since it has had a lot of unresolved issues for a long time now.
Stay safe and have a nice day!
